### ISSUE TITLE
Release 1.0

### ISSUE THREAD

**Issue by rovansteen** [scrnhq/laravel-bakery#33]
- [x] New API: Separate GraphQL logic from Eloquent with `ModelType` classes.
- [x] Order by relationships #23 
- [x] Add relationship count field #22 
- [x] Clean up public API #39
