### ISSUE TITLE
🌂 Version 2.0

### ISSUE THREAD

**Issue by rovansteen** [scrnhq/laravel-bakery#57]
We are well on our way to release a second version of Bakery which includes a brand new API that is much simpler and easier to use and enables us to support much more complex situations.

This issue contains all the things that needs to be done before releasing it.

### Features
- [x] Brand new API on top of `webonyx/graphql` (#51)
- [x] Pivot support (#51)
- [x] Polymorphic support (#51)
- [x] Automatic eager loading
- [x] More explicit, better typed API with model schemas (#75)
- [x] More user friendly installation (#80)
- [x] Auto discovery of model schemas (#80)
- [x] Documentation (#80)
- [x] Enum type support 
- [x] Union type support
- [ ] Scopes - _moved to 2.x_

### Bugs
- [x] Issue with nested lookup fields not working properly (#62)
- [x] Default routes can not be disabled in config file (#65)

@erikgaal anything else that needs to be on this list?

**Comment by erikgaal** [comment]
Released version 2.0.0 @ ae45da1
